In [17]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [18]:
df = pd.read_csv('C:\\Users\\92459\\Desktop\\DM92459\\01_heights_weights_genders.csv')

In [19]:
data

NameError: name 'data' is not defined

In [20]:
df

      Gender     Height      Weight
0       Male  73.847017  241.893563
1       Male  68.781904  162.310473
2       Male  74.110105  212.740856
3       Male  71.730978  220.042470
4       Male  69.881796  206.349801
5       Male  67.253016  152.212156
6       Male  68.785081  183.927889
7       Male  68.348516  167.971110
8       Male  67.018950  175.929440
9       Male  63.456494  156.399676
10      Male  71.195382  186.604926
11      Male  71.640805  213.741169
12      Male  64.766329  167.127461
13      Male  69.283070  189.446181
14      Male  69.243732  186.434168
15      Male  67.645620  172.186930
16      Male  72.418317  196.028506
17      Male  63.974326  172.883470
18      Male  69.640060  185.983958
19      Male  67.936005  182.426648
20      Male  67.915050  174.115929
21      Male  69.439440  197.731422
22      Male  66.149132  149.173566
23      Male  75.205974  228.761781
24      Male  67.893196  162.006652
25      Male  68.144033  192.343977
26      Male  69.089631  184.435174
27      Male  72.800844  206.828189
28      Male  67.421242  175.213922
29      Male  68.496415  154.342639
...      ...        ...         ...
9970  Female  65.618737  151.500389
9971  Female  64.640247  155.318297
9972  Female  60.653733  123.084293
9973  Female  60.737031  120.926500
9974  Female  65.393947  143.017835
9975  Female  66.251923  124.019917
9976  Female  61.475904  121.387236
9977  Female  64.494838  149.402547
9978  Female  57.375759  114.192209
9979  Female  62.056012  125.135897
9980  Female  60.472262  110.768229
9981  Female  60.443264  135.559390
9982  Female  69.868511  177.992066
9983  Female  65.830726  132.827889
9984  Female  59.047029  111.707369
9985  Female  68.041065  170.514213
9986  Female  63.352698  141.906510
9987  Female  65.610243  151.169475
9988  Female  59.538729  121.244876
9989  Female  60.955084   95.686674
9990  Female  63.179498  141.266100
9991  Female  62.636675  102.853563
9992  Female  62.077832  138.691680
9993  Female  60.030434   97.687432
9994  Female  59.098250  110.529686
9995  Female  66.172652  136.777454
9996  Female  67.067155  170.867906
9997  Female  63.867992  128.475319
9998  Female  69.034243  163.852461
9999  Female  61.944246  113.649103

[10000 rows x 3 columns]

In [21]:
data = pd.read_csv('C:\\Users\\92459\\Desktop\\DM92459\\brain_size')

FileNotFoundError: File b'C:\\Users\\92459\\Desktop\\DM92459\\brain_size' does not exist

In [22]:
data = pd.read_csv('C:\\Users\\92459\\Desktop\\DM92459\\brain_size.csv')

In [23]:
data

   ;"Gender";"FSIQ";"VIQ";"PIQ";"Weight";"Height";"MRI_Count"
0          1;"Female";133;132;124;"118";"64.5";816932
1             2;"Male";140;150;124;".";"72.5";1001121
2           3;"Male";139;123;150;"143";"73.3";1038437
3            4;"Male";133;129;128;"172";"68.8";965353
4          5;"Female";137;132;134;"147";"65.0";951545
5            6;"Female";99;90;110;"146";"69.0";928799
6          7;"Female";138;136;131;"138";"64.5";991305
7             8;"Female";92;90;98;"175";"66.0";854258
8               9;"Male";89;93;84;"134";"66.3";904858
9           10;"Male";133;114;147;"172";"68.8";955466
10        11;"Female";132;129;124;"118";"64.5";833868
11         12;"Male";141;150;128;"151";"70.0";1079549
12          13;"Male";135;129;124;"155";"69.0";924059
13        14;"Female";140;120;147;"155";"70.5";856472
14          15;"Female";96;100;90;"146";"66.0";878897
15           16;"Female";83;71;96;"135";"68.0";865363
16        17;"Female";132;132;120;"127";"68.5";852244
17           18;"Male";100;96;102;"178";"73.5";945088
18         19;"Female";101;112;84;"136";"66.3";808020
19             20;"Male";80;77;86;"180";"70.0";889083
20                  21;"Male";83;83;86;".";".";892420
21            22;"Male";97;107;84;"186";"76.5";905940
22        23;"Female";135;129;134;"122";"62.0";790619
23          24;"Male";139;145;128;"132";"68.0";955003
24          25;"Female";91;86;102;"114";"63.0";831772
25          26;"Male";141;145;131;"171";"72.0";935494
26           27;"Female";85;90;84;"140";"68.0";798612
27          28;"Male";103;96;110;"187";"77.0";1062462
28           29;"Female";77;83;72;"106";"63.0";793549
29        30;"Female";130;126;124;"159";"66.5";866662
30        31;"Female";133;126;132;"127";"62.5";857782
31          32;"Male";144;145;137;"191";"67.0";949589
32           33;"Male";103;96;110;"192";"75.5";997925
33             34;"Male";90;96;86;"181";"69.0";879987
34           35;"Female";83;90;81;"143";"66.5";834344
35        36;"Female";133;129;128;"153";"66.5";948066
36          37;"Male";140;150;124;"144";"70.5";949395
37           38;"Female";88;86;94;"139";"64.5";893983
38             39;"Male";81;90;74;"148";"74.0";930016
39             40;"Male";89;91;89;"179";"75.5";935863

In [24]:
    data = pd.read_csv('C:\\Users\\92459\\Desktop\\DM92459\\brain_size.csv')sep=';',na_values="."

SyntaxError: invalid syntax (<ipython-input-24-02041626a958>, line 1)

In [25]:
    data = pd.read_csv('C:\\Users\\92459\\Desktop\\DM92459\\brain_size.csv',    data = pd.read_csv('C:\\Users\\92459\\Desktop\\DM92459\\brain_size.csv')sep=';',na_values="." )

SyntaxError: invalid syntax (<ipython-input-25-d50190d5d6f8>, line 1)

In [26]:
data = pd.read_csv('C:\\Users\\92459\\Desktop\\DM92459\\brain_size.csv'sep=';',na_values=".")

SyntaxError: invalid syntax (<ipython-input-26-a299a57fe4ab>, line 1)

In [ ]:
data = pd.read_csv('C:\\Users\\92459\\Desktop\\DM92459\\brain_size.csv'sep=';',na_values=".")